name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mvn spring-boot:build-image
        docker tag docker.io/library/cloudplayground:0.0.1-SNAPSHOT fwilhe/cloudplayground:latest
    - name: Log into registry
      run: echo "${{ secrets.DH_PW }}" | docker login -u fwilhe --password-stdin
    - name: Push
      run: docker push fwilhe/cloudplayground:latest